//
//  JsonTags.h
//  ChargePoint
//
//  Created by Manish Kumar on 03/05/13.
//  Copyright (c) 2013 Chargepoint Inc.  All rights reserved.
//

#pragma mark - Functions
#define CONST_JSONTAG_MAPDATA                   @"map_data"
#define CONST_JSONTAG_PLACES_LIST               @"place"
#define CONST_JSONTAG_ADD_PLACE                 @"add_place"
#define CONST_JSONTAG_DELETE_PLACE              @"delete_place"
#define CONST_JSONTAG_EDIT_PLACE                @"edit_place"
#define CONST_JSONTAG_LIST_PLACE                @"list_place"
#define CONST_JSONTAG_NEARBY_STATION_LIST       @"nearby"
#define CONST_JSONTAG_ADD_TIP                   @"add_tip"
#define CONST_JSONTAG_START_SESSION             @"start_session"
#define CONST_JSONTAG_STOP_SESSION              @"stop_session"
#define CONST_JSONTAG_CHECK_SESSION_ACK         @"session_ack"
#define CONST_JSONTAG_RECENTLY_VISITED          @"recently_visited"

#define CONST_JSONTAG_ZOOM                      @"zoom"
#define CONST_JSONTAG_BOUNDS                    @"bound"
#define CONST_JSONTAG_MIN_LATITUDE              @"sw_lat"
#define CONST_JSONTAG_MIN_LONGITUDE             @"sw_lon"
#define CONST_JSONTAG_MAX_LATITUDE              @"ne_lat"
#define CONST_JSONTAG_MAX_LONGITUDE             @"ne_lon"
#define CONST_JSONTAG_SCREEN_WIDTH              @"screen_width"
#define CONST_JSONTAG_SCREEN_HEIGHT             @"screen_height"
#define CONST_JSONTAG_FILTER                    @"mobile_filter"
#define CONST_JSONTAG_LEVEL_ONE                 @"level1"
#define CONST_JSONTAG_LEVEL_TWO                 @"level2"
#define CONST_JSONTAG_PAID                      @"paid"
#define CONST_JSONTAG_FREE                      @"free"
#define CONST_JSONTAG_DEVICE_TIP                @"tip"
#define CONST_JSONTAG_FLAG_TIP                  @"flag_tip"
#define CONST_JSONTAG_DC_FAST                   @"dc"
#define CONST_JSONTAG_IN_NETWORK_STATION        @"in_network"
#define CONST_JSONTAG_OUT_OF_NETWORK            @"out_of_network"
#define CONST_JSONTAG_AVAILABLE                 @"available"
#define CONST_JSONTAG_IN_USE                    @"in_use"
#define CONST_JSONTAG_UNKNOWN                   @"unknown"
#define CONST_JSONTAG_RESERVABLE                @"reservable"
#define CONST_JSONTAG_NON_RESERVABLE            @"non_reservable"
#define CONST_JSONTAG_POWER_SHARING             @"power_sharing"
#define CONST_JSONTAG_NON_POWER_SHARING         @"non_power_sharing"
#define CONST_JSONTAG_LATITUDE                  @"lat"
#define CONST_JSONTAG_LONGITUDE                 @"lon"
#define CONST_JSONTAG_LIST_PAGE_OFFSET          @"page_offset"
#define CONST_JSONTAG_LIST_PAGE_SIZE            @"page_size"
#define CONST_JSONTAG_LIST_PLACE_COUNT          @"list_place_count"
#define CONST_JSONTAG_LIST_PLACE_PAGE_SIZE      @"list_place_page_size"
#define CONST_JSONTAG_DEVICE_ID                 @"device_id"
#define CONST_JSONTAG_TIP_ID                    @"tip_id"
#define CONST_JSONTAG_THUMBSUP_TIP              @"thumbs_up_tip"
#define CONST_JSONTAG_TIP_TEXT                  @"tip_text"
#define CONST_JSONTAG_STATION_IMAGE             @"station_image"
#define CONST_JSONTAG_STATION_PRICING_DETAIL    @"pricing_detail"
#define CONST_JSONTAG_STATION_INFO              @"station_info"
#define CONST_JSONTAG_STATION_PORT_STATUS       @"port_status"
#define CONST_JSONTAG_REFERENCE_LAT             @"reference_lat"
#define CONST_JSONTAG_REFERENCE_LON             @"reference_lon"
#define CONST_JSONTAG_USER_LAT                  @"user_lat"
#define CONST_JSONTAG_USER_LON                  @"user_lon"
#define CONST_JSONTAG_NAME                      @"name"
#define CONST_JSONTAG_DESCRIPTION               @"description"
#define CONST_JSONTAG_UPDATE_MEMBER_TIMESTAMP   @"update_member_timestamp"
#define CONST_JSONTAG_UPDATE_LIST_ORDER_TIMESTAMP  @"update_list_order_timestamp"
#define CONST_JSONTAG_PLACE_ID                  @"place_id"
#define CONST_JSONTAG_FULL                      @"full"
#define CONST_JSONTAG_USER_SERIAL               @"serial_number"
#define CONST_JSONTAG_PORT_NUMBER               @"port_number"
#define CONST_JSONTAG_TIMESTAMP                 @"timestamp"
#define CONST_JSONTAG_ACK_ID                    @"ack_id"
#define CONST_JSONTAG_SESSION_ACTION            @"session_action"
#define CONST_JSONTAG_USE_CACHE                 @"use_cache"
#define CONST_JSONTAG_USER_NAME                 @"user_name"
#define CONST_JSONTAG_PASSWORD                  @"password"